Remove unused variable.
`nchan` was set and maintained but never used in the `parse_zones` and
`parse_scanlist` functions for six radios, resulting in this error with
clang 15.0.0 and zig 0.11.0:

```plain
dm1801.c:1808:15: error: variable 'nchan' set but not used [-Werror,-Wunused-but-set-variable]
        int   nchan = 0;
```